### ISSUE TITLE
Implement dynamic function per batch

### ISSUE THREAD

**Issue by WWXkenmo** [martenlienen/torchode#15]
Hi, sorry for asking question once again, and thanks again for developing such wonderful tool.

as I mentioned in last issue (https://github.com/martenlienen/torchode/issues/13), I have decoupled a graph into several subgraph and batch them. For each subgraph (batch), I would have a specific ODE function for them, so I need to have a location parameter (i) to indicate the batch, and then output the function, probably like this:
```
class decoupled_dynamics(nn.Module):
    def func(t, h_v, phi_v):
        ...

    def forward(self, t: torch.Tensor, i: int):
        ## return the parameter for subgraph (subsystem) i
        h = self.h[i,:]
        phi = self.h[i,:]
        v = func(t,h,phi)

        return v
```
Then I am curious about how to initialise for each batch (subsystem)? seems according to the example code, all batch need to have the same ODE function?
```
term = to.ODETerm(f)
step_method = to.Dopri5(term=term)
step_size_controller = to.IntegralController(atol=1e-6, rtol=1e-3, term=term)
solver = to.AutoDiffAdjoint(step_method, step_size_controller)
jit_solver = torch.jit.script(solver)

sol = jit_solver.solve(to.InitialValueProblem(y0=y0, t_eval=t_eval))
```
Looking forward to your reply!

Best Regards,
Ken

**Comment by martenlienen** [comment]
Hi, if it is actually the same function just with different parameters for each batch, then you can use pytorch's broadcasting most likely.
```python
def linear_map(x, slope, intercept):
    return slope * x + intercept

x = torch.randn(2)
slope = torch.randn(2)
intercept = torch.randn(2)
# x has batch size 2 and you have defined different parameters (slope and intercept) for each sample
linear_map(x, slope, intercept)
```
In `torchode`, you can pass the batched parameters via args:
```python
def f(t, y, args):
    slope, intercept = args
term = to.ODETerm(f, with_args=True)
solver = to.AutoDiffAdjoint(..., term=term)
solver.solve(..., args=(slope, intercept))
```
If the function you want to evaluate is really completely different for each instance, you have to split the batch into the separate instances, for example with `y.unbind(batch_dim)`, compute the respective function on each sample and then stack the outputs again in the correct shape.
