### ISSUE TITLE
Jit error in readme example

### ISSUE THREAD

**Issue by chooron** [martenlienen/torchode#17]
Hello Marten Lienen, I encountered the same problem in issue #11 and I tried to debug it at the path `~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/torch/jit/recursive.py:393`. Initially, the code run at there with no error, but  when run again here, it gave the following error message: 
`{RuntimeError}Can't redefine method: init on class: __torch__.torchode.terms.ODETerm (of Python compilation unit at: 00000218DE53CC00)`. 
I am unsure if there are any issues with the ODETerm class, and I am hoping for your assistance.

Here is my installed package versions:
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.1
python-dateutil==2.8.2
six==1.16.0
sympy==1.11.1
torch==1.13.1
torchode==0.1.6
torchtyping==0.1.4
typeguard==2.13.3
typing_extensions==4.5.0

**Comment by martenlienen** [comment]
How did you run it again? Did you run the same file again with `python script.py` or did you run another cell in a Jupyter notebook? Running the same code back to back in the same python interpreter gave me no problems. If you are running it in an ipython shell or jupyter notebook and have code reloading enabled, that could be a problem. If you have modified the `term.py` file that defines `ODETerm`, ipython would reload it, redefining the `ODETerm` class under the same name which will confuse the JIT compiler.

**Comment by chooron** [comment]
Sorry, I may have made a mistake, what I meant was that when debugging the program, the code will pass the breakpoint twice, and in the first time the code does not report an error, while in the second time it will pop up this error.

**Comment by martenlienen** [comment]
Can you post the exact code here that you run? Because for me the code from the readme runs just fine.

**Comment by chooron** [comment]
Here is my code:
```
import matplotlib.pyplot as pp
import torch
import torchode as to

def f(t, y):
    return -0.5 * y

y0 = torch.tensor([[1.2], [5.0]])
n_steps = 10
t_eval = torch.stack((torch.linspace(0, 5, n_steps), torch.linspace(3, 4, n_steps)))

term = to.ODETerm(f)
step_method = to.Dopri5(term=term)
step_size_controller = to.IntegralController(atol=1e-6, rtol=1e-3, term=term)
solver = to.AutoDiffAdjoint(step_method, step_size_controller)
jit_solver = torch.jit.script(solver)

sol = solver.solve(to.InitialValueProblem(y0=y0, t_eval=t_eval))
print(sol.stats)
# => {'n_f_evals': tensor([26, 26]), 'n_steps': tensor([4, 2]),
# =>  'n_accepted': tensor([4, 2]), 'n_initialized': tensor([10, 10])}

pp.plot(sol.ts[0], sol.ys[0])
pp.plot(sol.ts[1], sol.ys[1])
pp.show()
```
If I delete `jit_solver = torch.jit.script(solver)`, it works out.

**Comment by martenlienen** [comment]
That is really curious. I have all the same package versions installed as you and for me the script runs without any issues.

**Comment by martenlienen** [comment]
If JIT compilation is important to you, you could try running it with pytorch 1.12. The JIT compiler has some issues in 1.13 that I was never really able to track down but where I had to exclude 1.13 from [certain tests](https://github.com/martenlienen/torchode/blob/main/tests/torch_script_test.py#L27-L30).

**Comment by chooron** [comment]
OK, I will try it later, thanks for your reply. If it not works, I will just use this package without JIT.
