### ISSUE TITLE
Support for pytorch 2.0?

### ISSUE THREAD

**Issue by rubick1896** [martenlienen/torchode#20]
I am trying to install the package with
`
pip install -e .
`
The installer uninstall my pytorch 2.0 and reinstalled pytorch 1.13, 
is that the only version of pytorch currently support?

**Comment by martenlienen** [comment]
I did not get around to testing it before now, but torchode is fully compatible, so I have released a new version that allows installing with pytorch 2.0. You can also use `torch.compile` with torchode instead of the older `torch.jit.script`.
