### ISSUE TITLE
Integrating 2 ODEs in parallel using torch.vmap

### ISSUE THREAD

**Issue by aravindshaj** [martenlienen/torchode#23]
I hope this message finds you well. I wanted to express my gratitude for your amazing repository. I was hoping to get some help with solving two ODEs in parallel using torchode and vmap class in functorch.

Below, I have attached a modified version of the example given in 'torchode/docs/jit.ipynb'. The code runs a for-loop and produces the desired output. However, when attempting to define an ensemble of models using vmap, it raises an error: "NotImplementedError: Module [AutoDiffAdjoint] is missing the required "forward" function".

    import torch
    import torch.nn as nn
    import torchode as to
    from functorch import combine_state_for_ensemble, vmap
    
    torch.random.manual_seed(180819023)

    class Model(nn.Module):
        def __init__(self, n_features, n_hidden):
            super().__init__()
            self.layers = nn.Sequential(
                nn.Linear(n_features, n_hidden),
                nn.Softplus(),
                nn.Linear(n_hidden, n_hidden),
                nn.Softplus(),
                nn.Linear(n_hidden, n_features)
            )
        
        def forward(self, t, y):
            return self.layers(y)

    n_features = 5
    model1 = Model(n_features=n_features, n_hidden=32)
    model2 = Model(n_features=n_features, n_hidden=32)

    dev = torch.device("cuda")
    
    term1 = to.ODETerm(model1)
    step_method1 = to.Dopri5(term=term1)
    step_size_controller1 = to.IntegralController(atol=1e-6, rtol=1e-3, term=term1)
    adjoint1 = to.AutoDiffAdjoint(step_method1, step_size_controller1).to(dev)
    
    term2 = to.ODETerm(model2)
    step_method2 = to.Dopri5(term=term2)
    step_size_controller2 = to.IntegralController(atol=1e-6, rtol=1e-3, term=term2)
    adjoint2 = to.AutoDiffAdjoint(step_method2, step_size_controller2).to(dev)
    
    adjoint_jit1 = torch.compile(adjoint1)
    adjoint_jit2 = torch.compile(adjoint2)
    
    batch_size = 3
    t_eval = torch.tile(torch.linspace(0.0, 3.0, 10), (batch_size, 1)).to(dev)
    y0 = torch.zeros((batch_size, 5)).to(dev)
    problem = to.InitialValueProblem(y0=y0, t_eval=t_eval)
    
    # running a simple for-loop
    models = [adjoint_jit1, adjoint_jit2]
    sol = [model.solve(problem) for model in models] # Works fine
    
    # defining an ensemble of models 
    fmodel, params, buffers = combine_state_for_ensemble(models)
    [p.requires_grad_() for p in params]
    
    sol_vmap = vmap(fmodel, in_dims=(0, 0, None))(params, buffers, problem) 
    # raises the error
    # NotImplementedError: Module [AutoDiffAdjoint] is missing the required "forward" function
    

I would appreciate any guidance on how I can move forward from here.

Thank you for your time and expertise.

**Comment by martenlienen** [comment]
Thank you for your kind words. I am sorry to disappoint you but torchode is not compatible with `torch.vmap`. If you see a way to make them work together, I am open for a contribution but I don't have the capacity at the moment to take care of this myself.
