### ISSUE TITLE
Alternative to Adjoint? + Implementation issues

### ISSUE THREAD

**Issue by Sergio20f** [martenlienen/torchode#27]
Hi,

Thanks for this amazing package! I have a few questions about its usage and implementation.

Firstly, is it possible to use a forward-only solver (i.e. not the adjoint method)? I am trying to prioritise speed as much as possible, and I don't really need to favour memory efficiency for my use case. Basically, are there alternatives to AutoDiffAdjoint?

Secondly, more specifically, I am trying to implement torchode instead of torchdiffeq in my particular model, however, I am struggling with this. The code in which I am trying to implement it is the following:

```
class ODEBlock(nn.Module):
    def __init__(self, odefunc, tol=1e-3, adjoint=False):
        super(ODEBlock, self).__init__()
        self.adjoint = adjoint
        self.odefunc = odefunc
        self.tol = tol

    def forward(self, x, time_emb, eval_times=None, method="rk4"):
        # Forward pass corresponds to solving ODE, so reset number of function
        # evaluations counter
        self.odefunc.nfe = 0

        if eval_times is None:
            integration_time = torch.tensor([0, 1]).float().type_as(x)
        else:
            integration_time = eval_times.type_as(x)

        if self.adjoint:
            out = odeint_adjoint(
                lambda t, x: self.odefunc(t, x, time_emb=time_emb),
                x,
                integration_time,
                rtol=self.tol,
                atol=self.tol,
                method=method,
                options={"max_num_steps": MAX_NUM_STEPS},
            )
        else:
            out = odeint(
                  lambda t, x: self.odefunc(t, x, time_emb=time_emb),
                 x,
                 integration_time,
                 rtol=self.tol,
                atol=self.tol,
                method=method,
                options={"max_num_steps": MAX_NUM_STEPS},
             )

        if eval_times is None:
            return out[1]  # out[1][:int(len(x)/2)]  Return only final time
        else:
            return out

    def trajectory(self, x, timesteps):
        integration_time = torch.linspace(0.0, 1.0, timesteps)
        return self.forward(x, eval_times=integration_time)
```
        
Where self.odefunc is the function approximation (basically a CNN in my case). As a naive attempt I tried to substitute the "odeint" by the following code:

```
           batch_size = 16
            n_steps = 10
            t_eval = torch.linspace(0.0, 1.0, n_steps)
            term = to.ODETerm(lambda t, x: self.odefunc(t, x, time_emb=time_emb))
            step_method = to.Dopri5(term=term)
            step_size_controller = to.IntegralController(
                atol=self.tol,
                rtol=self.tol,
                term=term
            )
            adjoint = to.AutoDiffAdjoint(step_method, step_size_controller).cuda()
            #adjoint_jit = torch.jit.script(adjoint)
            
            problem = to.InitialValueProblem(y0=x, t_eval=t_eval.repeat((batch_size, 1)))
            out = adjoint.solve(problem)
```

However, as I expected, this does not really work. Any comments or suggestions would greatly help me! Thanks a lot in advance!

**Comment by martenlienen** [comment]
I am glad that you like the package!

The terminology might be confusing but `AutoDiffAdjoint` does not use the "adjoint equation" for backpropagation but instead directly propagates through the solver implementation and is hand-optimized for performance. The adjoint equation is used in `BacksolveAdjoint` (so called because it solves the ODE backwards).

If you only care about the final state, you can set `t_eval = None` to short-circuit the whole evaluation logic and optimize the runtime even more as implemented here https://github.com/martenlienen/torchode/blob/022acecf6306fc939cbf76b168f597abbd320c82/torchode/adjoints.py#L215  and here https://github.com/martenlienen/torchode/blob/022acecf6306fc939cbf76b168f597abbd320c82/torchode/adjoints.py#L296-L301

All in all, I don't see any obvious problems. Can you specify what exactly isn't working?

Another piece of advice for you: You could or should initialize all the structures, i.e. `to.Dopri5` etc., only once in the constructor of your model and then reuse the same object each `forward` call.

**Comment by Sergio20f** [comment]
Thanks for your quick reply!

Great for the advice, I definitely will follow it.

Also, my bad for not including the specific error:

/usr/local/lib/python3.10/dist-packages/torchode/problems.py in __init__(self, y0, t_start, t_end, t_eval)
     43 
     44         if not torch.jit.is_scripting():
---> 45             assert y0.ndim == 2
     46             assert self.t_start.ndim == 1
     47             assert self.t_end.ndim == 1

AssertionError: 

To give more context, the self.odefunc(...) you can see in the class I included in my previous post is the following:

class ConvSODEFunc(nn.Module):
    def __init__(self, nf, time_dependent=False, non_linearity="relu",
                 time_emb_dim=None, groups=8):
        super(ConvSODEFunc, self).__init__()

        dim = nf
        dim_out = nf

        self.time_dependent = time_dependent
        self.nfe = 0  # Number of function evaluations

        self.mlp = nn.Sequential(
            nn.SiLU(),
            nn.Linear(time_emb_dim, dim_out * 2)
        ) if exists(time_emb_dim) else None

        if time_dependent:
            self.norm1 = nn.GroupNorm(groups, nf)
            self.conv1 = Conv2dTime(nf, nf, kernel_size=3, stride=1, padding=1)
            self.norm2 = nn.GroupNorm(groups, nf)
            self.conv2 = Conv2dTime(nf, nf, kernel_size=3, stride=1, padding=1)
        else:
            self.norm1 = nn.GroupNorm(groups, nf)
            self.conv1 = nn.Conv2d(nf, nf, kernel_size=3, stride=1, padding=1)
            self.norm2 = nn.GroupNorm(groups, nf)
            # Working with kernel size 1 and padding 0
            self.conv2 = nn.Conv2d(nf, nf, kernel_size=3, stride=1, padding=1)

        # 1x1 convolution used for the residual connection
        self.res_conv = nn.Conv2d(dim, dim_out, 1) if dim != dim_out else nn.Identity()

        self.non_linearity = get_nonlinearity(non_linearity)

    def forward(self, t, x, time_emb=None):
        scale_shift = None
        cutoff = int(x.shape[1] / 2)  # int(len(x)/2)
        # Typical in neural ODEs as they usually operate in anaugmented state space
        z = x[:, :cutoff]
        v = x[:, cutoff:]
        into = torch.cat((z, v), dim=1)
        self.nfe += 1

        if self.time_dependent:
            out = self.norm1(into)
            out = self.conv1(t, into)
            out = self.non_linearity(out)
            out = self.norm2(out)

            if exists(self.mlp) and exists(time_emb):
              time_emb = self.mlp(time_emb)
              time_emb = rearrange(time_emb, 'b c -> b c 1 1')
              scale_shift = time_emb.chunk(2, dim=1)
              scale, shift = scale_shift
              out = out * (scale + 1) + shift

            out = self.conv2(t, out)
            out = self.non_linearity(out)
        else:
            out = self.norm1(into)
            out = self.conv1(out)
            out = self.non_linearity(out)
            out = self.norm2(out)

            if exists(self.mlp) and exists(time_emb):
              time_emb = self.mlp(time_emb)
              time_emb = rearrange(time_emb, 'b c -> b c 1 1')
              scale_shift = time_emb.chunk(2, dim=1)
              scale, shift = scale_shift
              out = out * (scale + 1) + shift

            out = self.conv2(out)
            out = self.non_linearity(out)

        return out + self.res_conv(x)

Both of these are then used in my model class as follows:

in the __init__():

ode_down1 = ConvSODEFunc(nf * 2, time_dependent, non_linearity) # 
self.odeblock_down1 = ODEBlock(ode_down1, tol=tol, adjoint=adjoint)
self.conv_down1_2 = nn.Conv2d(nf * 2, nf * 4, 1, 1)

in the forward():
features1 = self.odeblock_down1(x, method=self.method, time_emb=t)

I understand that the issue comes from the dimensions of my input x, however I don't see how this differs from the usage with torchdiffeq :)

Any help is really appreciated. Thanks a lot!

**Comment by martenlienen** [comment]
The problem seems to be that your input tensor is not 2-dimensional. Because torchode handles the batch dimension explicitly, it expects all input tensors to be exactly of shape `batch x data`. If your data is not naturally a 1-dimensional vector, you have to reshape appropriately yourself. See the [doc page on the matter](https://torchode.readthedocs.io/en/latest/nd-data/).
