### ISSUE TITLE
Remove functorch as dependency

### ISSUE THREAD

**Issue by dawood95** [martenlienen/torchode#30]
https://github.com/martenlienen/torchode/blob/6883722dd4e14dd4d7a11fcc0da0eeabdff45fb6/pyproject.toml#L26

This currently causes pip to force a pytorch downgrade since functorch has a torch requirement of less than 2.1

**Comment by martenlienen** [comment]
Thanks for notifying me about this. I have released a new version 0.2.0 on pypi that requires at least pytorch 2.0 and no longer relies on the functorch interface.
