### ISSUE TITLE
Memory usage increase per iteration

### ISSUE THREAD

**Issue by m13ammed** [martenlienen/torchode#31]
I am trying to use the ode solver however i noticed that the memory usage keeps increasing (GPU memory) with each training iteration 

currently I have such pseudo code
```
class Model(Module):
     def __init__(*args,**kwargs):
       #definition of  layers 
       self.ODE_layer = CustomSequential(*layers) 
        self.regression_layer = nn.Conv1d(input_size, output_size, kernel_size=1, padding=0)
        term = torchode.ODETerm(self.ODE_layer)
        step_method = step_method(term=term)
        step_size_controller = step_size_controller(atol=1e-6, rtol=1e-3, term=term)
        solver = solver(step_method, step_size_controller)
        self.jit_solver = torch.compile(solver)

    def forward(inputs):

        sol = self.jit_solver.solve(torchode.InitialValueProblem(y0=inputs, t_eval=self.t_eval))

        outputs = self.regression_layer(sol.ys.permute(0,2,1)).permute(0,2,1)
        return outputs
```
CustomSequential is just a class that allows passing t into the sequential model. 

could the increased memory be caused by this setup (ie expected behavior)? 
Note: I used an identical pipeline without an ode solver (ie directly using the model as normal NN) and in that pipeline the memory is stable.

**Comment by martenlienen** [comment]
No, this is not expected and memory usage should not increase. However, such issues can be tricky to debug. Increasing memory usage means that, somewhere, references to old tensors are kept across training steps. In my experience, these are often backward graphs from previous training steps, but it could also be that somewhere tensors are accumulated in a list or dict internally (though I am not aware of any place in torchode where such a thing could happen).

Oh, one important thing, that could be happening: Is memory usage increasing more than expected? For many neural ODE models, the number of solver steps increases in training, which makes the backward graph bigger and increases memory usage over time. You can check the solver steps through `sol.stats`. You can also try `FixedStepController` for a controller that takes a fixed number of steps but can't adapt to the "local error rate" in solving the learned ODE.

**Comment by m13ammed** [comment]
Thank you for your feedback. I confirmed either fixing the step size or relaxing the tolerance fix the issue.

**Comment by Ilykuleshov** [comment]
Opened new issue #40
