### ISSUE TITLE
Question on Backwards Mode

### ISSUE THREAD

**Issue by m13ammed** [martenlienen/torchode#38]
I aim to solve a final value problem. As I read the implementation, the backward mode would solve a final value problem, right? I need to ensure that t_start > t_end and t_eval go in descending order. Or have I misunderstood something, and I would need more significant modifications?

**Comment by martenlienen** [comment]
Hey, to solve a final value problem, you apply torchode as normal in forward mode, just making sure that the conditions you name hold. Backward is for backpropagation, i.e. computation of gradients, and has nothing to do with the direction in which you solve the ODE.

Best,
Marten
