### ISSUE TITLE
python>=3.10 ?

### ISSUE THREAD

**Issue by sijieaaa** [martenlienen/torchode#4]
Hi,

May I know if torchode only supports python>=3.10?

![image](https://user-images.githubusercontent.com/58644619/204510494-a606aad4-58ca-4252-a78b-8653d1cce8ca.png)

My Envs:
Ubuntu 20.04
python 3.8
torch 1.11.0
CUDA 11.6

Thanks!

**Comment by martenlienen** [comment]
At the moment, torchode requires python 3.10, but I think that is mostly because of the `list[...]` and `tuple[...]` type annotations.

**Comment by martenlienen** [comment]
I have released version 0.1.2 that is compatible with python 3.8. Let me know if it works for you.
