### ISSUE TITLE
Memory consumption increasing

### ISSUE THREAD

**Issue by Ilykuleshov** [martenlienen/torchode#40]
Firstly, thank you for such a great library!
My issue is, the memory consumption is constantly increasing between batches in the adjoint method. Something to consider, one of the arguments I pass in as the solver's args field requires gradient. Could this be the culprit?

**Comment by Ilykuleshov** [comment]
No, that wasn't it. It is not BacksolveAdjoint either. It is most likely a memory leak within the pytorch autograd Function's context ctx, see https://stackoverflow.com/questions/67471019/memory-leak-in-pytorch-autograd-function-when-assigning-and-returning-context-da

**Comment by martenlienen** [comment]
The snippet in the linked question runs with constant memory for me on pytorch 2.2.2. Do you have a minimal example that showcases the increasing memory requirements?

**Comment by Ilykuleshov** [comment]
After some more snooping around, found pytorch/pytorch#25340, this might be the issue. Sorry, still can't make a proper minimal example

**Comment by Ilykuleshov** [comment]
Torchmetrics was the culprit, sorry to disturb you
