### ISSUE TITLE
Documentation of ODE solvers

### ISSUE THREAD

**Issue by tuchris** [martenlienen/torchode#43]
Hi and thanks for the fast ODE-solver,

I recently started using your solver and could easily reproduce your examples and setup the solver. However, I do not find any documentation about the three (?) available ODE-solvers (AutoDiffAdjoint, BacksolveAdjoint, JointBacksolveAdjoint). Coincidentally I stumbled about your linked response in a former issue which gives some insights. 

I am wondering, if I missed some documentation or if it is not described anywhere (except a brief statement in the accompanying papers appendix)? In the latter case, would it be possible to add some information on the documenation website?

Thanks and hoping to help future new users with these insights.

BR

"
The terminology might be confusing but `AutoDiffAdjoint` does not use the "adjoint equation" for backpropagation but instead directly propagates through the solver implementation and is hand-optimized for performance. The adjoint equation is used in `BacksolveAdjoint` (so called because it solves the ODE backwards).
"

_Originally posted by @martenlienen in https://github.com/martenlienen/torchode/issues/27#issuecomment-1672242414_

**Comment by martenlienen** [comment]
Thank you for the suggestion! I have added a new page to the docs: https://torchode.readthedocs.io/en/latest/backprop/
